# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[project]
name = "mot-toolkit"
version = "1.4.0"
description = "MOT Toolkit"
authors = [
    { name = "Haomin Kong", email = "a645162@qq.com" }
]
dependencies = [
    "loguru",
    "GitPython",
    "tqdm",
    "progressbar2",
    "numpy<2.0.0",
    "opencv-python",
    "chardet",
    "PyYaml",
    "toml",
    "psutil",
]
readme = "README.md"
readme-content-type = "text/markdown"
#license = { text = "GPLv3" }
license = { file = "LICENSE" }
requires-python = ">= 3.8"
maintainers = [
    { name = "Haomin Kong", email = "a645162@qq.com" }
]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = [
    "MOT", "mot",
    "tracking", "tracker",
    "tracking toolkit"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://github.com/a645162/mot-toolkit"
Documentation = "https://github.com/a645162/mot-toolkit/blob/main/README.zh-CN.md"
Repository = "https://github.com/a645162/mot-toolkit.git"
Issues = "https://github.com/a645162/mot-toolkit/issues"
Changelog = "https://github.com/a645162/mot-toolkit/blob/main/CHANGELOG.md"
DOWNLOAD = "https://github.com/a645162/mot-toolkit/releases"

[project.scripts]
mot-toolkit = "mot_toolkit.main_gui:main"
mot-toolkit-tools = "mot_toolkit.tools:main"
mot-toolkit-spilt = "mot_toolkit.gui.view.interface.spilt.spilt_cli:main"

# 动态替换 README.md 中的链接
#[tool.hatch.metadata.hooks.readme]
#content-type = "text/markdown"
#path = "README.md"

#[[tool.hatch.metadata.hooks.readme.replacements]]
#pattern = r"$README\.zh-CN\.md$"
#replacement = "https://github.com/a645162/mot-toolkit/blob/main/README.zh-CN.md"

[tool.hatch.build.targets.sdist]
include = ["LICENSE", "README.md"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/mot_toolkit"]
#source-dirs = ["src"]

[project.optional-dependencies]
gui = [
    "qtpy",
    "pyside6",
    "pygame",
]

dl = [
    "torch",
    "torchvision",
    "ultralytics>=8.3.0",
]

dataset = [
    "torchvision",
    "pillow",
    "opencv-python",
    "scikit-learn",
    "mmengine",
]

crawler = [
    "playwright"
]

# TrackEval
## https://github.com/JonathonLuiten/TrackEval
## https://github.com/a645162/TrackEvalNew
eval = [
    "numpy>=1.18.1",
    "scipy>=1.4.1",
    "pycocotools>=2.0.2",
    "matplotlib>=3.2.1",
    "opencv_python>=4.4.0.46",
    "scikit_image>=0.16.2",
    "pytest>=6.0.1",
    "Pillow>=8.1.2",
    "tqdm>=4.64.0",
    "tabulate",
]

dev = [
    "ruff",
    "flake8",
    "pre-commit",
    "pytest",
    "pyinstaller",
    "nuitka",
    "cairosvg",
    "pip_search",
]

[tool.rye]
managed = true
dev-dependencies = [
    "hatchling",
    "ruff",
    "cairosvg",
    "pytest",
    "pyinstaller",
    "nuitka>=2.4.8",
    "pillow>=10.4.0",
]

[tool.poetry.group.dl.dependencies]
torch = ">=2.0.0"
torchvision = ">=0.10.0"
ultralytics = ">=8.3.0"

[tool.uv]
dev-dependencies = [
    "hatchling",
    "ruff",
    "cairosvg",
    "pytest",
    "pyinstaller",
    "nuitka>=2.4.8",
    "pillow>=10.4.0",
]

[tool.poetry]
dev-dependencies = [
    "hatchling",
    "ruff",
    "cairosvg",
    "pytest",
    "pyinstaller",
    "nuitka>=2.4.8",
    "pillow>=10.4.0",
]

# Rye Source
[[tool.rye.source]]
name = "HuaWei"
url = "https://mirrors.huaweicloud.com/pypi/simple"
priority = "primary"

[[tool.rye.source]]
name = "Tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple"
priority = "explicit"

[[tool.rye.source]]
name = "Tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "explicit"

#[[tool.rye.source]]
#name = "USTC"
#url = "https://mirrors.ustc.edu.cn/pypi/web/simple"
#priority = "explicit"

# Poetry Source
[[tool.poetry.source]]
name = "HuaWei"
url = "https://mirrors.huaweicloud.com/pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "Tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple"
priority = "explicit"

[[tool.poetry.source]]
name = "Tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "explicit"

#[[tool.poetry.source]]
#name = "USTC"
#url = "https://mirrors.ustc.edu.cn/pypi/web/simple"
#priority = "explicit"
